# This allows you to change the messages file. Useful if you want to change a language without 
# modifying the same config every time
message-file: messages-en.yml

# Permission Based Shops
permission-based-shops: 
    enabled: false
    permission: "shopgui.shop.{shopname}"

# When in the shop inventories, should empty slots be filled with stained glass panes?
shop-fill-empty-slots: true