main: net.dxtrus.shopgui.ShopGUI
name: ShopGUI
version: 1.0.0.0-SNAPSHOT
depend: [Vault]

commands:
    shopgui:
        aliases: [shop]
        description: The main command for ShopGUI. Use /shop for the shop itself.
        usage: /<command> [args]